# nixpacks.toml - The definitive configuration for a Discord.js bot on Railway's Nixpacks builder

# Phase 1: Setup the Environment
# This explicitly tells Nixpacks to install Node.js version 18 AND the system libraries for 'canvas'.
[phases.setup]
nixPkgs = ["nodejs-18_x", "pkgs.cairo", "pkgs.pango", "pkgs.libjpeg", "pkgs.giflib", "pkgs.pkg-config"]

# Phase 2: Install Node.js Dependencies
# This will now run in an environment where 'npm' exists.
[phases.install]
cmds = ["npm install"]

# Phase 3: Build & Deploy Commands
# This runs after all dependencies are successfully installed.
[phases.build]
cmds = ["npm run deploy"]

# Phase 4: Start the Bot
# This is the final command that runs your live application.
[start]
cmd = "npm start"
