# nixpacks.toml - The definitive configuration for a Discord.js bot with 'canvas' on Railway's Nixpacks builder

# Phase 1: Setup System Dependencies
# This uses the Nix package manager (`nixPkgs`), which is the core of the Nixpacks builder.
# It is the most reliable way to install the required system libraries for 'canvas'.
[phases.setup]
nixPkgs = ["pkgs.cairo", "pkgs.pango", "pkgs.libjpeg", "pkgs.giflib", "pkgs.pkg-config"]

# Phase 2: Install Node.js Dependencies
# This runs after the system libraries are available, ensuring 'canvas' can build correctly.
[phases.install]
cmds = ["npm install"]

# Phase 3: Build & Deploy Commands
# This runs after all dependencies are installed.
[phases.build]
cmds = ["npm run deploy"]

# Phase 4: Start the Bot
# This is the final command that runs your live application.
[start]
cmd = "npm start"
