# nixpacks.toml - Correct configuration for installing canvas on Railway

[phases.setup]
# System packages required by the 'canvas' library, installed via Nix
nixPkgs = ["pkgs.cairo", "pkgs.pango", "pkgs.libjpeg", "pkgs.giflib", "pkgs.pkg-config"]

# This phase installs your Node.js dependencies after the system libraries are in place.
[phases.install]
cmds = ["npm install"]

# This phase builds your application by deploying commands.
[phases.build]
cmds = ["npm run deploy"]

# This phase defines the command to start your application.
[start]
cmd = "npm start"
