# nixpacks.toml - The Definitive Final Version

# This tells Nixpacks to use the Node.js provider.
providers = ["node"]

# This phase installs Node.js version 18 itself, PLUS the required system libraries.
# This is the line that was missing and caused all the failures.
[phases.setup]
nixPkgs = ["nodejs-18_x", "pkgs.cairo", "pkgs.pango", "pkgs.libjpeg", "pkgs.giflib", "pkgs.pkg-config"]

# This phase runs after Node.js is installed. It will now find `npm`.
[phases.install]
cmds = ["npm install"]

# This phase runs after dependencies are installed.
[phases.build]
cmds = ["npm run deploy"]

# This is the final command to start your bot.
[start]
cmd = "npm start"
