# nixpacks.toml

[phases.build]
# System packages required by the 'canvas' library
aptPkgs = ["build-essential", "libcairo2-dev", "libpango1.0-dev", "libjpeg-dev", "libgif-dev", "librsvg2-dev"]
# Commands to run during the build phase, in order
cmds = ["npm install", "npm run deploy"]

[start]
# The command to start the bot after the build is complete
cmd = "npm start"
